# Generated by Django 3.0 on 2020-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member3_classes',
            field=models.CharField(default='abc', max_length=10),
        ),
    ]
