# Generated by Django 3.0 on 2020-02-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_team_member3_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member3_classes',
            field=models.CharField(max_length=10),
        ),
    ]
