# Generated by Django 3.0 on 2020-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('boss_name', models.CharField(max_length=4)),
                ('boss_phone', models.CharField(max_length=13)),
                ('boss_classes', models.CharField(max_length=10)),
                ('boss_num', models.CharField(max_length=12)),
                ('team_members', models.CharField(max_length=2)),
                ('member2_name', models.CharField(max_length=4)),
                ('member2_num', models.CharField(max_length=12)),
                ('member2_classes', models.CharField(max_length=10)),
                ('member3_name', models.CharField(max_length=4)),
                ('member3_num', models.CharField(max_length=12)),
                ('member3_classes', models.CharField(max_length=10)),
            ],
        ),
    ]
